/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface _tamachi_db_stateRow {
  "schemaVersion": number 
}
export interface audioRow {
  "id"?: number | null 
  "sentenceId": number 
  "language": string 
  "speaker": string 
  "base64": string 
  "created": number 
}
export interface linkstorysentenceRow {
  "id"?: number | null 
  "sentenceId": number 
  "storyId": number 
  "idx": string 
}
export interface reviewRow {
  "id"?: number | null 
  "userId": number 
  "sentenceId": number 
  "epoch": number 
  "results": string 
}
export interface sentenceRow {
  "id"?: number | null 
  "ja": string 
  "jaHint": string 
  "en": string 
}
export interface storyRow {
  "id"?: number | null 
  "title": string 
}
export interface userRow {
  "id"?: number | null 
  "name": string 
  "hashed": string 
  "salt": string 
  "iterations": number 
  "keylen": number 
  "digest": string 
}
